name: custom_uploader
description: Allows you to upload files to a custom server
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.2+12

environment:
  sdk: '>=3.5.0 <4.0.1'
  flutter: '3.27.3'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  file_picker: ^6.0.0
  percent_indicator: ^4.2.2
  xml: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0 # contains Isar Core
  pluto_grid: ^8.0.0
  flutter_markdown: ^0.6.12
  receive_sharing_intent: ^1.4.5
  url_launcher: ^6.1.6
  permission_handler: ^11.4.0
  device_info_plus: ^11.2.1
  package_info_plus: ^8.2.1
  yaml: ^3.1.2
  mime: ^1.0.0
  http_parser: ^4.1.2
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  assets:
    - lib/assets/contents.md
    - lib/assets/preset_uploaders.yaml
  uses-material-design: true
