name: custom_uploader
description: Allows you to upload files to a custom server.flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+5

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  file_picker: ^5.2.2
  percent_indicator: ^4.2.2
  xml: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0 # contains Isar Core
  pluto_grid: ^5.4.9
  flutter_markdown: ^0.6.12
  receive_sharing_intent: ^1.4.5
  url_launcher: ^6.1.6
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  assets:
    - lib/views/markdown/contents.md
  uses-material-design: true
