name: custom_uploader
description: Allows you to upload files to a custom server.flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+6

environment:
  sdk: '>=2.18.2 <4.0.1'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  file_picker: ^6.0.0
  percent_indicator: ^4.2.2
  xml: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0 # contains Isar Core
  pluto_grid: ^7.0.2
  flutter_markdown: ^0.6.12
  receive_sharing_intent: ^1.4.5
  url_launcher: ^6.1.6
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  assets:
    - lib/views/markdown/contents.md
  uses-material-design: true
