name: custom_uploader
description: Allows you to upload files to a custom server
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+13

environment:
  sdk: '>=3.5.0 <4.0.1'
  flutter: '3.29.3'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  dio: ^5.4.0
  dio_cache_interceptor: ^4.0.3
  file_picker: ^10.2.0
  percent_indicator: ^4.2.5
  xml: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0 # contains Isar Core
  pluto_grid: ^8.0.0
  flutter_sharing_intent: ^1.1.1
  url_launcher: ^6.1.6
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  yaml: ^3.1.2
  mime: ^2.0.0
  http_parser: ^4.1.2
  path_provider: ^2.0.1
  pure_ftp: ^0.7.5
  flutter_speed_dial: ^7.0.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.15
  intl_utils: ^2.8.2

flutter:
  generate: true
  assets:
    - lib/assets/preset_uploaders.yaml
  uses-material-design: true
