name: Bug Report
description: Found something in Custom Uploader you weren't expecting? Report it here!
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >
        NOTE: Make sure you are using the latest release and take a moment to
        check that your issue hasn't been reported before.
  - type: textarea
    id: description
    attributes:
      label: Describe The Bug
      description: |
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: description-reproduce
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavoir
    attributes:
      label: Expected Behavior
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Log Gist
      description: Please provide a gist URL of your logs, with any sensitive
        information (e.g. API keys) removed/hidden
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If this issue involves the Web Interface, please provide one or
        more screenshots
  - type: input
    id: os-ver
    attributes:
      label: OS Version
      description: Your current version of Android you are running
    validations:
      required: true
  - type: input
    id: app-ver
    attributes:
      label: App Version
      description: Your current version of Custom Uploader
    validations:
      required: true
