name: Feature Request
description: Got an idea for a feature that Custom Uploader doesn't have currently? Submit your idea here!
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        NOTE: Please take a moment to check that your feature hasn't already been suggested.
  - type: textarea
    id: description
    attributes:
      label: Feature Description
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If you can, provide screenshots of an implementation on another site e.g. GitHub
