name: Question
description: Got a question about Custom Uploader? Ask it here!
labels: ["help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        NOTE: Please take a moment to check that your question hasn't already been asked.
  - type: textarea
    id: description
    attributes:
      label: Question
      description: A clear and concise description of what you want to ask
    validations:
      required: true
