name: Flutter Build Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_android:
    name: Build Flutter App (Android)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build App Bundle
        run: flutter build appbundle --release

  build_ios:
    name: Build Flutter App (iOS)
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS (no code signing)
        run: |
          sudo xcode-select -s /Applications/Xcode_15.3.app
          flutter build ipa --release --no-codesign
